#!/usr/bin/env bash

# Use extended and eager saved and shared history
export HISTSIZE=50000
export HISTFILESIZE=500000

# Set my editor to nano:
export EDITOR=nano

# load all my aliases
source $HOME/.dotfiles/bash/bash_aliases
source $HOME/.dotfiles/bash/functions

# Important for easy setting of terminal colours. Needed now for tig colours to work:
export TERM=xterm-256color
export PATH=/usr/local/php5/bin:$PATH:/Users/tawandanyakudjga/.composer/vendor/bin
source /usr/local/opt/nvm/nvm.sh
